name: Test Setups

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/test-setups.yml"
      - "installers/*_setup.sh"
  pull_request:
    branches: [ main ]

jobs:

  fedora:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Test Fedora Setup
      run: sh test/fedora/test.sh installers/fedora_setup.sh

  rocky:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Test Rocky Setup
        run: sh test/rocky/test.sh installers/rocky_setup.sh
